config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :followers
  devise_for :users
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :users, only: %i[index show create] do
    resources :followers, only: %i[create destroy]
  end
  resources :opinions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  delete 'reject', to: 'followers#reject'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :opinions
  has_many :followers
  has_many :inverse_followers, class_name: 'Follower', foreign_key: 'follower_id'
  has_one_attached :avatar
  has_one_attached :cover_image
  has_many :confirmed_followers, -> { where confirmed: true }, class_name: 'Follower'
  has_many :friends, through: :confirmed_followers
  has_rich_text :body

  def friends
    follower_array = followers.map(&:follower)
    follower_array.concat(inverse_followers.map(&:user))
    follower_array.compact
  end

  def confirmed_followers(user)
    follower = inverse_followerss.find { |inv_follower| inv_follower.user == user }
    follower.confirmed = true
    follower.save
  end

  def friend?(user)
    friends.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include TheUser
  before_action :set_user
  before_action :authenticate_user!
  before_action :user_signed_in?

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @new_opinion = Opinion.new

    respond_to do |format|
      if @user
        format.html
        format.js
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def show_last; end
end

app/helpers/users_helper.rb
module UsersHelper
  def follow(user)
    if current_user.id == user.id || current_user.friend?(user)
      nil
    else
      link_to 'Follow', user_followers_path(@user), method: :post, value: '1'
    end
  end

  def avatar
    if @user.avatar.attached?
      image_tag @user.avatar.variant(resize: '90x90!')
    else
      image_tag('profile.png', class: 'rounded-circle', height: 90, width: 90)
    end
  end

  def user_cover
    if @user.cover_image.attached?
      image_tag @user.cover_image, class: 'col-12 p-0', style: 'height: 15em'
    else
      image_tag('cover.jpg', class: 'col-12 p-0', style: 'height: 15em')
    end
  end

  def current_avatar
    if current_user.avatar.attached?
      image_tag current_user.avatar.variant(resize: '90x90!'), class: 'rounded-circle'
    else
      image_tag('profile.png', class: 'rounded-circle', height: 90, width: 90)
    end
  end

  def resources_avatar
    if resource.avatar.attached?
      image_tag resource.avatar.variant(resize: '90x90!'), class: 'rounded-circle'
    else
      image_tag('profile.png', class: 'rounded-circle', height: 90, width: 90)
    end
  end

  def resources_cover
    if resource.cover_image.attached?
      image_tag resource.cover_image.variant(resize: '90x90!'), class: 'rounded-circle'
    else
      image_tag('profile.png', height: 90, width: 90)
    end
  end

  def same_follower
    if !current_user.friend?(@user)
      nil
    else
      link_to 'Unfollow', reject_path(user_id: @user.id, follower_id: current_user.id), method: :delete
    end
  end
end

app/views/users/_feed.html.erb
<div class="container">

  <% @opinions.each do | opinion | %>
    <% if current_user %>
      <%= link_to  opinion.user.name, user_path(opinion.id), remote: true%>
      <% else %>
    <%= link_to  opinion.user.name, user_path(opinion.user.id), remote: true%>
    <% end %>
    <%= opinion.body %>
    <%= opinion.created_at.strftime('%A, %B %e,%Y') %>
    <tr>
      <td><%= link_to 'Show', opinion %></td>
      <td><%= link_to 'Edit', edit_opinion_path(opinion) %></td>
      <td><%= link_to 'Destroy', opinion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>

</div>

app/views/users/_form.html.erb
<%= form_with(model: @new_opinion, local: true) do |form| %>
  <div class="p-3 m-3 trix">
    <div>
      <%= form.rich_text_area :body, label: "What's Your Opinion", input_html: {class: "textarea"}, wrapper: false, label_html: {class: "label"}, placeholders: "Your opinion...", autofocus: true %>
    </div>

  <%= hidden_field_tag(:redirect_url, user_path(@user.id)) %>
  <%= form.button :submit, class: "btn btn-secondary mt-2"   %>
  </div>
<% end %>

app/views/users/_full_profile.html.erb
<div class="container pt-5  who-to-follow">
  <div class="col-12 align-content-center pt-4">

    <div style="text-align: center" >
      <div class="p-1 ">
        <%= avatar %>
      </div>
    </div>


    <div class=" justify-content-center " style=" text-align: center">
      <h5 class="card-title"><%= @user.name %></h5>
      <p class="card-text"><small class="text-muted"><%= "@#{@user.username}" %></small></p>
    </div>
    <ul class="dropdown col-12 " style="text-align: center">
      <li class="btn btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        More
      </li>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="#">
          <div class="col-4 " >
            <%=  follow(@user) %>
          </div></a>
        <a class="dropdown-item" href="#">
          <div class="col-4 " >
            <%= link_to 'Profile',  user_path(@user) %>
          </div>
        </a>
        <a class="dropdown-item" href="#">
          <div class="col-4">
            <%= same_follower %>
          </div>
        </a>
      </div>
    </ul>
  </div>
  <hr>
  <div class="col-12 row mt-5" style="text-align: center">
    <div class="col-4">
      <p>Following</p>
      <%= @user.followers.count %>
    </div>
    <div class="col-4">
      <p>Followers</p>
      <%= @user.inverse_followers.count %>
    </div>
    <div class="col-4">
      <p>Opinions</p>
      <%= current_user.opinions.count %>
    </div>
  </div>
  <hr>
  <div class="col-12 mt-5">
    <div class="media-body">
      <div class="row justify-content-center ">
        <h6>Followed By</h6>
      </div>
      <hr/>
    </div>
    <div>
      <% @user.inverse_followers.each do |person| %>

        <div class="col-12">
          <%= link_to person.user.name, user_path(person.user.id)  %>
        </div>
          <hr>
      <% end %>
    </div>

  </div>
</div>

app/views/users/_profile.html.erb
<div class="container pt-3 pr-0">
  <div class="col-12 row align-items-baseline justify-content-center ">
    <div class="col-4  avatar">
      <%= current_avatar %>
    </div>
    <div class=" justify-content-center col-8 " style=" text-align: center">
      <h5 class="card-title text-white"><%= current_user.name %></h5>
      <p class="card-text text-white"><small class="text-muted"><%= "@#{current_user.username}" %></small></p>
    </div>
  </div>
  <hr>
  <div class="col-12 text-white row mt-5">
    <div class="col-6 ">
      <p>Following</p>
      <%= current_user.followers.count %>
    </div>
    <div class="col-6">
      <p>Followers</p>
      <%= current_user.inverse_followers.count %>
    </div>

  </div>
</div>
<hr>

app/views/users/_user.html.erb
<div id="user" class="users ">
  <%= render "users/full_profile" %>
</div>

app/views/users/_user_feed.html.erb
<div id="feed" class="list-group ml-3 pr-5" >
  <% @user.opinions.order("created_at DESC").each do | opinion | %>
    <div  class="list-group-item list-group-item-action my-1 rounded ">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"><%= link_to  opinion.user.name, user_path(opinion.user.id), remote: true%></h5>
        <hr>
        <small><%= opinion.created_at.strftime('%c') %></small>
      </div>
      <p class="mb-1"><%= opinion.body %></p>
    </div>
  <% end %>
</div>

app/views/users/_user_tab_nav.html.erb
<ul class="nav nav-tabs text-muted" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Home</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Photos</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Followers</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Following</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Favorites</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Lists</a>
  </li>
</ul>
<%= render 'users/form' %>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab"><%= render 'users/user_feed' %></div>
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">...</div>
  <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>
</div>

app/views/users/show.html.erb
<div class="container row col-12 p-0 m-0">
  <div class="content col-3 p-0 m-0">
    <nav class="side_nav" style="width: 100%">
      <ul>
        <ul class="text-muted">
          <li><a href="/"><i class="fa fa-home" aria-hidden="true"></i><%= link_to 'Home', opinions_path %></a></li>
          <hr>
          <li><a href="/"><i class="fa fa-connectdevelop" aria-hidden="true"></i>Connect</a></li>
          <hr>
          <li><a href="/"><i class="fa fa-podcast" aria-hidden="true"></i>Discover</a></li>
          <hr>
          <li><a href="/"><i class="fa fa-stumbleupon" aria-hidden="true"></i>Statistics</a></li>
        </ul>
      </ul>
    </nav>
  </div>
  <div class="col-9 p-0">
    <%= render 'opinions/navbar' %>
    <div class="col-12 row m-0 p-0">
      <div class="col-8 p-0">
        <%= user_cover %>
        <%= render 'users/user_tab_nav' %>
      </div>
      <div class="col-4 pl-0">
        <%= render 'users/full_profile' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.js.erb
$('#user').fadeIn();

$('#user').append("<%= j render  @user %>").html_safe

$(document).ready(function(){
    $(window).click(function(){$('#user').fadeOut();});
});