config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :followers
  devise_for :users
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :users, only: %i[index show create] do
    resources :followers, only: %i[create destroy]
  end
  resources :opinions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  delete 'reject', to: 'followers#reject'
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :user
  belongs_to :follower, class_name: 'User'
end

app/controllers/followers_controller.rb
# rubocop: disable Style/IfUnlessModifier

class FollowersController < ApplicationController
  before_action :set_follower, only: %i[show edit update destroy]

  # GET /followers
  # GET /followers.json
  # def index
  #   @followers = Follower.all
  # end

  # GET /followers/1
  # GET /followers/1.json
  # def show
  # end

  # # GET /followers/new
  # def new
  #   @follower = Follower.new
  # end

  # # GET /followers/1/edit
  # def edit
  # end

  # POST /followers
  # POST /followers.json
  def create
    @follower = current_user.followers.build(follower_id: params[:user_id], confirmed: true)

    if @follower.save
      redirect_to user_path(id: @follower.follower_id), notice: 'Following successful.'
    else
      redirect_to opinions_path, alert: @follower.errors.full_messages.join('. ').to_s
    end
  end

  # PATCH/PUT /followers/1
  # PATCH/PUT /followers/1.json
  # def update
  #   respond_to do |format|
  #     if @follower.update(follower_params)
  #       format.html { redirect_to @follower, notice: 'Follower was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @follower }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @follower.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /followers/1
  # DELETE /followers/1.json
  def reject
    @follower = Follower.find_by(follower_id: params[:follower_id], user_id: params[:user_id])
    if @follower.nil?
      @follower = Follower.find_by(follower_id: params[:user_id], user_id: params[:follower_id])
    end
    @follower.destroy
    redirect_to opinions_path, notice: 'Unfollowed'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_follower
    @follower = Follower.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def follower_params
    params.require(:follower).permit(:user_id, :follower_id, :confirmed)
  end
end

# rubocop: enable Style/IfUnlessModifier

app/helpers/followers_helper.rb
module FollowersHelper
end

app/views/followers/_form.html.erb
<%= form_with(model: follower, local: true) do |form| %>
  <% if follower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(follower.errors.count, "error") %> prohibited this follower from being saved:</h2>

      <ul>
        <% follower.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :follower_id %>
    <%= form.text_field :follower_id %>
  </div>

  <div class="field">
    <%= form.label :confirmed %>
    <%= form.check_box :confirmed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/followers/edit.html.erb
<h1>Editing Follower</h1>

<%= render 'form', follower: @follower %>

<%= link_to 'Show', @follower %> |
<%= link_to 'Back', followers_path %>

app/views/followers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Followers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Follower</th>
      <th>Confirmed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @followers.each do |follower| %>
      <tr>
        <td><%= follower.user_id %></td>
        <td><%= follower.follower_id %></td>
        <td><%= follower.confirmed %></td>
        <td><%= link_to 'Show', follower %></td>
        <td><%= link_to 'Edit', edit_follower_path(follower) %></td>
        <td><%= link_to 'Destroy', follower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Follower', new_follower_path %>

app/views/followers/new.html.erb
<h1>New Follower</h1>

<%= render 'form', follower: @follower %>

<%= link_to 'Back', followers_path %>

app/views/followers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @follower.user_id %>
</p>

<p>
  <strong>Follower:</strong>
  <%= @follower.follower_id %>
</p>

<p>
  <strong>Confirmed:</strong>
  <%= @follower.confirmed %>
</p>

<%= link_to 'Edit', edit_follower_path(@follower) %> |
<%= link_to 'Back', followers_path %>